### ISSUE TITLE
Require access to the older version of scPred

### ISSUE THREAD

**Issue by mohit1997** [powellgenomicslab/scPred#11]
Is there any way to install the older versions (1.0.0) of scPred? My code was written in that version but I accidentally updated my scPred installation. It seems like the older API was much different than the current one. Can you help me with this?

**Comment by joseah** [comment]
Hi,

You can install the previous version of `scPred` with

 ```r
devtools::install_github("powellgenomicslab/scPred", ref = "1.0")
```

Let me know if you have any issues.

**Comment by mohit1997** [comment]
Thanks a lot! It worked.

**Comment by mohit1997** [comment]
Hi, I am using the older version of scPred and am facing this error "Error: The tuning parameter grid should have columns sigma, C". I see that this was fixed in a commit, can you integrate that commit with this version `devtools::install_github("powellgenomicslab/scPred", ref = "1.0")`?
