### ISSUE TITLE
trainModel function (version 1.9.0) 

### ISSUE THREAD

**Issue by ceesu** [powellgenomicslab/scPred#12]
Hello, I am following the latest version of your introduction vignette with the most up to date version of scPred. However I don't seem to be able to go fast the trainModel step.
For me, the input to trainModel is Seurat object and the output of trainModel appears to be a Seurat object with 1 feature only. I also cannot run methods such as "get_probabilities" and "scPredict" on the output. The error seems to be:
`could not find function "get_probabilities"`
I wonder if trainModel has failed silently on my dataset. How could I check this?

**Comment by joseah** [comment]
Hi @ceesu, the trained models are stored in the `@misc` slot of Seurat object. What is the output of

```R
get_scpred(seurat_object)
```
?

> `get_scpred()` is an accessor method to get the scPred models from Seurat objects

You mention you have only 1 feature in your object. Does the number of features in the Seurat object change after `trainModel()`?

**Comment by ceesu** [comment]
This is the output:

`Error: 'get_scpred' is not an exported object from 'namespace:scPred'
Traceback:

1. scPred::get_scpred
2. getExportedValue(pkg, name)
3. stop(gettextf("'%s' is not an exported object from 'namespace:%s'", 
 .     name, getNamespaceName(ns)), call. = FALSE, domain = NA)`

Or if I use scPred directly:

`Error in get_scpred(reference): could not find function "get_scpred"`

**Comment by ceesu** [comment]
For the second question -- yes, before the trainModel step the object has `50281 features across 50846 samples within 1 assay`; afterwards I have 
`1 features across 50846 samples within 1 assay `
Is it possible that the step has failed silently because of memory issues?

**Comment by ceesu** [comment]
Hmm, both of the commands you gave me give output NULL but packageVersion("scPred") gives me ‘1.9.0’.

**Comment by joseah** [comment]
What's the output of `reference@misc$scPred`?

**Comment by ceesu** [comment]
Here's an extract of it:


$expVar
       PC_1        PC_2        PC_3        PC_4        PC_5        PC_6 
0.213997846 0.086776192 0.079815775 0.062717986 0.054118324 0.045462126 
       PC_7        PC_8        PC_9       PC_10       PC_11       PC_12 
0.037647785 0.032645951 0.027273174 0.024354222 0.020770640 0.019200491 
      PC_13       PC_14       PC_15       PC_16       PC_17       PC_18 
0.016841737 0.015777828 0.014894537 0.014443250 0.013980986 0.012859154 
      PC_19       PC_20       PC_21       PC_22       PC_23       PC_24 


And in the features slot there is many features that look like this:

$features$Sst
      PC        pValue     pValueAdj     expVar cumExpVar
1   PC_1  0.000000e+00  0.000000e+00 0.21399785 0.2139978
2   PC_3  0.000000e+00  0.000000e+00 0.07981578 0.2938136
3   PC_5  0.000000e+00  0.000000e+00 0.05411832 0.3479319

**Comment by ceesu** [comment]
The output also seems to include the training results? Which begins as:

$pVar
[1] "subclass_label.valid"

$pseudo
[1] FALSE

$train
$train$Sst
Support Vector Machines with Class Weights 

No pre-processing
Resampling: Cross-Validated (5 fold) 
Summary of sample sizes: 40677, 40677, 40677, 40676, 40677 
Resampling results across tuning parameters:

  C     Weight  AUC         Precision  Recall     F        
  0.25  1       0.99625604  0.9805856  0.9838780  0.9822229
  0.25  2       0.04203093  0.9746938  0.9913372  0.9829403

**Comment by joseah** [comment]
This is odd, it looks that you have an older version. To verify, could you run 

```r
grep("scPred", devtools::session_info(), value = TRUE)
```

?

**Comment by ceesu** [comment]
Hmm, however I actually just reinstalled the package today this morning because I was thinking this might be the case. The output is:

`1' V scPred       * 0.0.0.9000 2020-09-28 [1]'2' Github (powellgenomicslab/scPred@32bc593)'`

**Comment by joseah** [comment]
You definitely have an older version. Try installing the new version using the info from the README file (https://github.com/powellgenomicslab/scPred) and let me know if you run into the same errors.

**Comment by ceesu** [comment]
Ok, maybe I need to reinstall a second time. I'll keep you updated, thanks.

**Comment by ceesu** [comment]
Oh, also, can I ask about the training process? In my case, I have one dataset that I am manually splitting into a train/test combination. 
Is running NormalizeData() on the reference and query separately in each case equivalent to running NormalizeData() on the combination of reference and query?

**Comment by joseah** [comment]
Yes, you can normalize the data first using the whole object and splitting the data afterwards too.
If you run into some issues with the new version, please feel free to open another issue.
