### ISSUE TITLE
Error in getFeatureSpace(reference, "cell_type")

### ISSUE THREAD

**Issue by shangyf-stu** [powellgenomicslab/scPred#13]
I have followed introduction of scPred. Then, I just change a new input data and don`t change anything. The codes can work well in my PC, but An error occurred while running on the server.
    Error in getFeatureSpace(reference, "cell_type") : 
      no slot of name "metadata" for this object of class "Seurat"
Any help? Thanks a lot!

**Comment by shangyf-stu** [comment]
On the other hand, I can't get pbmc_1 and pbmc_2 contained by this package.  Is it a clue means I should reinstall scPred

**Comment by joseah** [comment]
Hi @shangyf-stu, it seems that you have an older version of `scPred` installed in the server you're using (`pbmc_1` and `pbmc_2` are not exported in previous versions). I recommend installing the latest version via `devtools` as described in the README file.

**Comment by shangyf-stu** [comment]
Thanks for your attention, I'll try it right now!
