### ISSUE TITLE
Error: The tuning parameter grid should have columns sigma, C

### ISSUE THREAD

**Issue by CongqianyouYz** [powellgenomicslab/scPred#3]
Hi,

I downloaded scPred by install_github and constructed SingleCellExperiment object using my own data. But at trainModel step, it turned like:

"Error: The tuning parameter grid should have columns sigma, C"

Any idea about this error? The only difference between my script and tutorial is that SingleCellExperiment object.

**Comment by joseah** [comment]
Hi @CongqianyouYz, thanks for your feedback! This error should be solved with commit `c716bbe` (current state of the repo). Let me know if you still experience some issues.
José
