### ISSUE TITLE
Documentation for scPredict states wrong newData format?

### ISSUE THREAD

**Issue by FloWuenne** [powellgenomicslab/scPred#5]
Hi,

I was implementing scPred in a shiny app today and was going over the documentation for the scPredict function. It states there:

`newData | A matrix object with cells as rows and genes (loci) as columns`

But it actually takes the inverse, cells as columns and genes as rows. This is also how it is shown in your tutorial, the train and test data are both in the format: columns = cells, rows = genes.

I just wanted to make sure that I have this correct and it might be worth updating the manual for scPredict to avoid confusion! 

Thanks again for a very nice package!

**Comment by joseah** [comment]
Hi @FloWuenne, thank you so much for reporting this issue!
This has been solved in commit **e3e8eb3**.
